name: CI

on:
  workflow_dispatch:

jobs:
  annotations:
    runs-on: ubuntu-latest
    name: An example job
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: ./
      with:
        token: '${{secrets.GITHUB_TOKEN}}'
